#!/bin/bash

build() {
  add_binary "/bin/plymouth"
  add_binary "/sbin/plymouthd"
  add_binary "$(readlink -e /lib/libnss_files.so.2)"
  add_file "/lib/libnss_files.so.2" 
  add_file "/etc/plymouth/plymouthd.conf"
  add_file "/etc/passwd"
  add_file "/etc/system-release"
  add_file "/etc/bsswitch.conf"
  add_file "/usr/share/plymouth/themes/text/text.plymouth"
  add_file "/usr/share/plymouth/themes/details/details.plymouth"
}

helpmsg() {
  cat<<HELPEOF
This builder includes support for Plymouth
HELPEOF
}

# vim: set et ts=2 sw=2:
